package com.lib_dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lib_dao.bean.PlayListInfo;

import com.lib_dao.db.PlayListInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playListInfoDaoConfig;

    private final PlayListInfoDao playListInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playListInfoDaoConfig = daoConfigMap.get(PlayListInfoDao.class).clone();
        playListInfoDaoConfig.initIdentityScope(type);

        playListInfoDao = new PlayListInfoDao(playListInfoDaoConfig, this);

        registerDao(PlayListInfo.class, playListInfoDao);
    }
    
    public void clear() {
        playListInfoDaoConfig.clearIdentityScope();
    }

    public PlayListInfoDao getPlayListInfoDao() {
        return playListInfoDao;
    }

}
